=== ivaivalous/cfollow/communication-schema/server-message-schema.v1.json
{
	"title": "Cfollow Server Message JSON Schema",
	"type": "object",
	"$schema":  "http://json-schema.org/draft-03/schema",
	"required": true,
	"properties": {
		"apiKey":  {
			"description": "API key used by the cfollow client, returned by the server",
			"type": "string",
			"required": true
		},
		"customDatabaseQuery": {
			"description": "Execute a custom SQL query. The server must make sure the query is safe to use",
			"type": "string",
			"required": false
		},
		"silent": {
			"description": "If true, no response will be returned by the cfollow client but configuration changes and SQL requests will be performed. Default is false",
			"type": "boolean",
			"required": false
		},
		"serverTime": {
			"description": "ISO-8601 date as configured on the server. The client will override its time to this",
			"type": "string",
			"required": false
		},
		"connectionsRequest":  {
			"description": "An object to configure what the client needs to supply in terms of connections",
			"type": "object",
			"required": false,
			"properties": {
				"count": {
					"description": "Number of records to return. If missing, no connections will be given in client response but proposed configuration will be applied",
					"type": "number",
					"required": false
				},
				"defaultCount": {
					"description": "Number of records to return by default in initiating request",
					"type": "number",
					"required": false
				},
				"index":  {
					"description": "Starting index for the response to this message. Will start from 0 if empty",
					"type": "number",
					"required": false
				},
				"newOnly": {
					"description": "Whether to only return new (not-snchonized) records. Defaults to false",
					"type": "boolean",
					"required": false
				},
				"reconnectIntervalMinutes": {
					"description": "Set the interval at which a connection should be reattempted",
					"type": "number",
					"required": false
				}
			}
		},
		"positionsRequest":  {
			"type": "object",
			"required": false,
			"properties": {
				"count": {
					"description": "Number of records to return. If missing, no positions will be given in client response but proposed configuration will be applied",
					"type": "number",
					"required": false
				},
				"gpsLocationMinutes": {
					"description": "Set the interval at which a GPS coordinates should be registered",
					"type": "number",
					"required": false
				},
				"gpsModuleStop": {
					"description": "If true stops the GPS module until sent as false",
					"type": "boolean",
					"required": false
				},
				"index": {
					"description": "Starting index for the response to this message. Will start from 0 if empty",
					"type": "number",
					"required": false
				},
				"newOnly": {
					"description": "Whether to only return new (not-snchonized) records. Defaults to false",
					"type": "boolean",
					"required": false
				}
			}
		}
	}
}

=== ivaivalous/cfollow/communication-schema/examples/server-message-example.json
{
	"apiKey": "777-ivo-555",
	"serverTime": "2007-03-01T13:00:00Z",
	"connectionsRequest": {
		"index": 0,
		"count": 5,
		"defaultCount": 5,
		"newOnly": false,
		"reconnectIntervalMinutes": 30
	},
	"positionsRequest": {
		"index": 0,
		"count": 5,
		"defaultCount": 5,
		"newOnly": false,
		"gpsLocationMinutes": 30,
		"gpsModuleStop": false
	},
	"customDatabaseQuery": "",
	"silent": true
}
